"use client"

import { motion } from "framer-motion"
import { Download, FileJson, FileText, Copy, Share2, CheckCircle } from "lucide-react"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { toast } from "sonner"
import { generateGasPDF } from "@/lib/pdf-generator"
import type { GasAnalysisData } from "./gas-profiler-experience"

interface GasExportActionsProps {
    data: GasAnalysisData
}

export function GasExportActions({ data }: GasExportActionsProps) {
    const [copied, setCopied] = useState(false)

    const handleExportJSON = () => {
        const json = JSON.stringify(data, null, 2)
        const blob = new Blob([json], { type: "application/json" })
        const url = URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = `mantleguard-analysis-${Date.now()}.json`
        a.click()
        URL.revokeObjectURL(url)
        toast.success("Analysis exported as JSON")
    }

    const handleExportPDF = () => {
        try {
            generateGasPDF({
                totalGas: data.totalGas,
                daFee: data.daFee,
                estimatedMNT: data.estimatedMNT,
                optimizationScore: data.optimizationScore,
                functions: data.functions.map(f => ({
                    name: f.name,
                    gas: f.gas,
                    severity: f.severity,
                    estimatedSavings: f.estimatedSavings
                })),
                optimizations: data.optimizations.map(opt => ({
                    severity: opt.severity,
                    problem: opt.problem,
                    suggestion: opt.suggestion,
                    estimatedSavings: opt.estimatedSavings
                }))
            })
            toast.success("PDF report generated successfully!")
        } catch (error) {
            toast.error("Failed to generate PDF report")
        }
    }

    const handleCopyAnalysis = async () => {
        const summary = `
MantleGuard Gas Analysis Report
================================

Total Gas: ${data.totalGas.toLocaleString()}
DA Fee: ${data.daFee.toFixed(4)} ETH
Estimated MNT: ${data.estimatedMNT.toFixed(2)}
Optimization Score: ${data.optimizationScore}/100

Function Analysis:
${data.functions.map(f => `- ${f.name}: ${f.gas.toLocaleString()} gas (${f.severity} severity)`).join("\n")}

Optimization Opportunities: ${data.optimizations.length}
Potential Savings: ${data.optimizations.reduce((sum, opt) => {
            const match = opt.estimatedSavings.match(/-?(\d+)%/)
            return sum + (match ? parseInt(match[1]) : 0)
        }, 0)}%

Generated by MantleGuard - https://mantleguard.app
        `.trim()

        try {
            await navigator.clipboard.writeText(summary)
            setCopied(true)
            toast.success("Analysis copied to clipboard")
            setTimeout(() => setCopied(false), 2000)
        } catch (error) {
            toast.error("Failed to copy to clipboard")
        }
    }

    const handleShareResults = async () => {
        const shareData = {
            title: "MantleGuard Gas Analysis",
            text: `Gas Analysis: ${data.totalGas.toLocaleString()} gas | Optimization Score: ${data.optimizationScore}/100`,
            url: window.location.href
        }

        if (navigator.share) {
            try {
                await navigator.share(shareData)
                toast.success("Analysis shared successfully")
            } catch (error) {
                // User cancelled or error occurred
            }
        } else {
            // Fallback: copy link
            try {
                await navigator.clipboard.writeText(window.location.href)
                toast.success("Link copied to clipboard")
            } catch (error) {
                toast.error("Sharing not supported")
            }
        }
    }

    const actions = [
        {
            label: "Export JSON",
            icon: FileJson,
            onClick: handleExportJSON,
            description: "Download full analysis data"
        },
        {
            label: "Export PDF",
            icon: FileText,
            onClick: handleExportPDF,
            description: "Generate PDF report"
        },
        {
            label: copied ? "Copied!" : "Copy Analysis",
            icon: copied ? CheckCircle : Copy,
            onClick: handleCopyAnalysis,
            description: "Copy summary to clipboard"
        },
        {
            label: "Share Results",
            icon: Share2,
            onClick: handleShareResults,
            description: "Share with your team"
        }
    ]

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/5 to-white/[0.02] p-6 backdrop-blur-sm"
        >
            <div className="flex items-center gap-3 mb-6">
                <div className="p-2 rounded-xl bg-primary/10">
                    <Download className="w-5 h-5 text-primary" />
                </div>
                <div>
                    <h3 className="font-semibold text-white">Export & Share</h3>
                    <p className="text-sm text-muted-foreground">
                        Save or share your analysis results
                    </p>
                </div>
            </div>

            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {actions.map((action, index) => {
                    const Icon = action.icon

                    return (
                        <motion.div
                            key={action.label}
                            initial={{ opacity: 0, scale: 0.9 }}
                            animate={{ opacity: 1, scale: 1 }}
                            transition={{ duration: 0.3, delay: index * 0.1 }}
                        >
                            <Button
                                variant="outline"
                                onClick={action.onClick}
                                className="w-full h-auto flex-col items-start gap-3 p-4 rounded-2xl hover:bg-white/5 hover:border-primary/30 transition-all group"
                            >
                                <div className="flex items-center gap-3 w-full">
                                    <div className="p-2 rounded-lg bg-white/5 group-hover:bg-primary/10 transition-colors">
                                        <Icon className="w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors" />
                                    </div>
                                    <span className="font-medium text-sm">{action.label}</span>
                                </div>
                                <p className="text-xs text-muted-foreground text-left w-full">
                                    {action.description}
                                </p>
                            </Button>
                        </motion.div>
                    )
                })}
            </div>

            {/* Quick stats */}
            <div className="mt-6 pt-6 border-t border-white/10">
                <div className="grid grid-cols-3 gap-4 text-center">
                    <div>
                        <p className="text-xs text-muted-foreground mb-1">Functions</p>
                        <p className="text-lg font-bold text-white tabular-nums">{data.functions.length}</p>
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground mb-1">Issues Found</p>
                        <p className="text-lg font-bold text-white tabular-nums">{data.optimizations.length}</p>
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground mb-1">Potential Savings</p>
                        <p className="text-lg font-bold text-emerald-400 tabular-nums">
                            {data.optimizations.reduce((sum, opt) => {
                                const match = opt.estimatedSavings.match(/-?(\d+)%/)
                                return sum + (match ? parseInt(match[1]) : 0)
                            }, 0)}%
                        </p>
                    </div>
                </div>
            </div>
        </motion.div>
    )
}
