export interface ShareOptions {
    title: string
    description: string
    url?: string
    data?: any
}

export async function shareToGitHub(options: ShareOptions): Promise<void> {
    const { title, description, data } = options

    // Format issue body with analysis data
    const issueBody = `
## Security Analysis Report

${description}

### Key Findings
${data?.issues?.slice(0, 5).map((issue: any, i: number) =>
        `${i + 1}. **${issue.severity.toUpperCase()}**: ${issue.title}\n   - ${issue.description}`
    ).join('\n') || 'No issues found'}

### Scores
- Security Score: ${data?.securityScore || 'N/A'}/100
- Total Issues: ${data?.issuesCount || 0}

---
*Generated by MantleGuard - AI Security Auditing for Mantle Network*
    `.trim()

    // Create GitHub issue URL with pre-filled data
    const githubUrl = `https://github.com/new/issue?title=${encodeURIComponent(title)}&body=${encodeURIComponent(issueBody)}`

    window.open(githubUrl, '_blank')
}

export async function shareToTwitter(options: ShareOptions): Promise<void> {
    const { title, description, url, data } = options

    // Create tweet text
    const tweetText = `${title}

Security Score: ${data?.securityScore || 'N/A'}/100
Issues Found: ${data?.issuesCount || 0}

${description}

#MantleNetwork #SmartContractSecurity #Web3Security

${url || window.location.href}`

    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}`
    window.open(twitterUrl, '_blank')
}

export async function shareViaEmail(options: ShareOptions): Promise<void> {
    const { title, description, data } = options

    const emailBody = `
${title}

${description}

Security Score: ${data?.securityScore || 'N/A'}/100
Total Issues: ${data?.issuesCount || 0}

${data?.issues?.slice(0, 3).map((issue: any, i: number) =>
        `${i + 1}. ${issue.severity.toUpperCase()}: ${issue.title}\n   Impact: ${issue.impact}\n`
    ).join('\n') || ''}

View full report: ${window.location.href}

---
Generated by MantleGuard AI Security Suite
https://mantleguard.app
    `.trim()

    const subject = encodeURIComponent(title)
    const body = encodeURIComponent(emailBody)

    window.location.href = `mailto:?subject=${subject}&body=${body}`
}

export async function shareToForum(options: ShareOptions): Promise<void> {
    const { title, description, data } = options

    // Format for forum post (BBCode style)
    const forumPost = `[b]${title}[/b]

${description}

[b]Security Analysis Results:[/b]
• Security Score: ${data?.securityScore || 'N/A'}/100
• Total Issues Found: ${data?.issuesCount || 0}
• Critical Issues: ${data?.criticalCount || 0}
• High Issues: ${data?.highCount || 0}

[b]Top Issues:[/b]
${data?.issues?.slice(0, 3).map((issue: any, i: number) =>
        `${i + 1}. [color=#FF0000]${issue.severity.toUpperCase()}[/color]: ${issue.title}\n   ${issue.description}`
    ).join('\n\n') || 'No critical issues found'}

Full Report: ${window.location.href}

---
[i]Generated by MantleGuard - AI-Powered Smart Contract Security[/i]`

    // Copy to clipboard for easy pasting
    try {
        await navigator.clipboard.writeText(forumPost)
        alert('Forum post copied to clipboard! You can now paste it on any forum.')
    } catch (error) {
        console.error('Failed to copy forum post', error)
        alert('Failed to copy forum post. Please try again.')
    }
}

export async function generateGitHubAction(): Promise<void> {
    const yamlContent = `name: MantleGuard Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install MantleGuard CLI
        run: npm install -g @mantleguard/cli
      
      - name: Run Security Audit
        run: |
          mantleguard audit contracts/**/*.sol \\
            --output audit-report.json \\
            --fail-on critical,high
        env:
          MANTLEGUARD_API_KEY: \${{ secrets.MANTLEGUARD_API_KEY }}
      
      - name: Upload Audit Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-audit-report
          path: audit-report.json
      
      - name: Comment PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('audit-report.json', 'utf8'));
            
            const comment = \`## 🛡️ MantleGuard Security Audit
            
            **Security Score:** \${report.securityScore}/100
            **Issues Found:** \${report.issuesCount}
            
            ### Critical Issues: \${report.criticalCount}
            ### High Issues: \${report.highCount}
            
            [View Full Report](\${report.reportUrl})
            \`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: comment
            });
`

    const blob = new Blob([yamlContent], { type: 'text/yaml' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'mantleguard-audit.yml'
    a.click()
    URL.revokeObjectURL(url)
}

export async function generateAPIWebhook(): Promise<void> {
    const webhookExample = `// MantleGuard Webhook Integration Example

const express = require('express');
const app = express();

app.use(express.json());

// Webhook endpoint to receive MantleGuard audit results
app.post('/webhooks/mantleguard', (req, res) => {
  const auditResult = req.body;
  
  console.log('Received audit result:', auditResult);
  
  // Process the audit result
  if (auditResult.securityScore < 70) {
    // Send alert to your team
    sendAlert({
      severity: 'HIGH',
      message: \`Security score is low: \${auditResult.securityScore}/100\`,
      issues: auditResult.issues
    });
  }
  
  // Store in database
  storeAuditResult(auditResult);
  
  res.status(200).json({ received: true });
});

// Configure webhook in MantleGuard:
// URL: https://your-domain.com/webhooks/mantleguard
// Secret: your-webhook-secret
// Events: audit.completed, gas.analyzed

app.listen(3000, () => {
  console.log('Webhook server running on port 3000');
});

// API Integration Example
const axios = require('axios');

async function submitContractForAudit(contractCode) {
  try {
    const response = await axios.post('https://api.mantleguard.app/v1/audit', {
      contract: contractCode,
      options: {
        severity: ['critical', 'high', 'medium'],
        mantleOptimizations: true
      }
    }, {
      headers: {
        'Authorization': 'Bearer YOUR_API_KEY',
        'Content-Type': 'application/json'
      }
    });
    
    return response.data;
  } catch (error) {
    console.error('Audit failed:', error);
  }
}
`

    const blob = new Blob([webhookExample], { type: 'text/javascript' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'mantleguard-webhook-integration.js'
    a.click()
    URL.revokeObjectURL(url)
}

export async function generateCLICommands(): Promise<void> {
    const cliGuide = `# MantleGuard CLI Tools

## Installation

\`\`\`bash
npm install -g @mantleguard/cli
\`\`\`

## Authentication

\`\`\`bash
mantleguard auth login
# Or use API key
export MANTLEGUARD_API_KEY="your-api-key"
\`\`\`

## Basic Commands

### Security Audit
\`\`\`bash
# Audit a single contract
mantleguard audit contracts/MyContract.sol

# Audit all contracts in a directory
mantleguard audit contracts/**/*.sol

# Audit with specific severity levels
mantleguard audit contracts/*.sol --severity critical,high

# Output to JSON
mantleguard audit contracts/*.sol --output report.json

# Fail CI on issues
mantleguard audit contracts/*.sol --fail-on critical,high
\`\`\`

### Gas Analysis
\`\`\`bash
# Analyze gas consumption
mantleguard gas contracts/MyContract.sol

# Compare with baseline
mantleguard gas contracts/*.sol --compare baseline.json

# Generate optimization suggestions
mantleguard gas contracts/*.sol --optimize
\`\`\`

### Report Generation
\`\`\`bash
# Generate PDF report
mantleguard report --input audit.json --format pdf

# Generate markdown report
mantleguard report --input audit.json --format md

# Generate HTML report
mantleguard report --input audit.json --format html --open
\`\`\`

### Integration
\`\`\`bash
# Initialize project configuration
mantleguard init

# Setup GitHub Actions
mantleguard setup github-action

# Setup pre-commit hook
mantleguard setup pre-commit

# Configure webhook
mantleguard webhook configure --url https://your-domain.com/webhook
\`\`\`

## Configuration File (.mantleguard.json)

\`\`\`json
{
  "contracts": ["contracts/**/*.sol"],
  "severity": ["critical", "high", "medium"],
  "mantleOptimizations": true,
  "gasThreshold": 1000000,
  "excludeContracts": ["contracts/mocks/**"],
  "output": {
    "format": "json",
    "destination": "./reports"
  },
  "ci": {
    "failOnSeverity": ["critical", "high"],
    "commentOnPR": true
  }
}
\`\`\`

## Advanced Usage

### Watch Mode
\`\`\`bash
# Continuously audit contracts on file changes
mantleguard audit contracts/*.sol --watch
\`\`\`

### Diff Mode
\`\`\`bash
# Compare two audit results
mantleguard diff audit-before.json audit-after.json
\`\`\`

### Export to Platform
\`\`\`bash
# Export to GitHub Security
mantleguard export github-security

# Export to Notion
mantleguard export notion --workspace your-workspace

# Export to Slack
mantleguard export slack --channel #security
\`\`\`

---
For more information, visit: https://docs.mantleguard.app
`

    const blob = new Blob([cliGuide], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'mantleguard-cli-guide.md'
    a.click()
    URL.revokeObjectURL(url)
}
